### ISSUE TITLE
couple of tests failed in csaransh-pp_test

### ISSUE THREAD

**Issue by ManojWarrier** [haptork/csaransh#5]
A couple of tests are failing when we run csaransh-pp_test from the _build directory. This is because the "data" directory is at one level above the "_build" directory. All tests pass when I run csaransh-pp_test from the directory above the "_build" directory.

**Comment by haptork** [comment]
Added directions to run test in the Readme mentioning that the tests should be run from the csaransh_pp directory only. f0dc8b653e85cfb5e6e8cb4639ae10da3b9a8cf9
