### ISSUE TITLE
Documentation - Post processing of data

### ISSUE THREAD

**Issue by ManojWarrier** [haptork/csaransh#6]
In the section "Post processing of data" of the documentation there exist two post-processors, namely
(i) csaransh_pp which acts on data/*/*.xyz files which creates "cascades-data.json" file which is useful for analysis of 
    (a) number of defects
    (b) their distribution
    (c) clustering,
    (d) correlations, etc., and
(ii) pp.py in the csaransh-pp directory which acts on the "cascades-data.json" file to classify the defect clusters (persumably).

It might be worth mentioning what each of these does in one line. If one does not want to carry out the classification, can they still load the data and analyse the data? how does one go about it?

**Comment by haptork** [comment]
In addition to classification, the python post-processor adds subcascades information, PCA information etc.
Currently, the web page expects all of the data. So, one needs to run both the post-processors. However, it might be useful to make the UI and methods modular in future. 

The information on what the two post-processors do will be a good addition. Feel free to take it up and send a PR. I'm assigning this to you.

**Comment by ManojWarrier** [comment]
How do you think II should do it? Do I fork the project, modify the REDME.md, push it to the forked branch and then submit a pull request? Any other way? This is new to me.
